=== paohaijiao/jquick-java/src/main/resources/paohaijiao/dtd/Jquick-java.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT javas (java*)>
        <!ATTLIST javas namespace CDATA #REQUIRED>

        <!ELEMENT java (#PCDATA|if|foreach|choose)*>
        <!ATTLIST java
                name CDATA #REQUIRED
                returnClass CDATA #REQUIRED
                >

        <!ELEMENT code (#PCDATA)>

        <!ELEMENT if (#PCDATA | if | foreach | choose)*>
        <!ATTLIST if test CDATA #REQUIRED>

        <!ELEMENT foreach (#PCDATA | if | foreach | choose)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #REQUIRED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when*, otherwise?)>
        <!ELEMENT when (#PCDATA | if | foreach | choose)*>
        <!ATTLIST when test CDATA #REQUIRED>
        <!ELEMENT otherwise (#PCDATA | if | foreach | choose)*>

=== paohaijiao/jquick-java/src/test/jquick-java.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE javas PUBLIC "-//PAOHAIJIAO//DTD API JAVA 1.0//EN"
        "classpath:paohaijiao/dtd/Jquick-java.dtd">
<javas namespace="com.github.paohaijiao.test.xml.UserApi">
    <java name="all" returnClass="java.util.List">

    </java>

    <java name="getUserById" returnClass="com.github.paohaijiao.test.model.JUser">

    </java>
    <java name="getUserByIdVariable" returnClass="com.github.paohaijiao.test.model.JUser">
        <if test="a==1"> -H "Content-Type: application/json" </if>
    </java>

    <java name="users" returnClass="com.github.paohaijiao.test.model.JUser">

    </java>
    <java name="usersByVariable" returnClass="com.github.paohaijiao.test.model.JUser">
    </java>

    <java name="usersPut" returnClass="com.github.paohaijiao.test.model.JUser">
    </java>

    <java name="usersPatch" returnClass="com.github.paohaijiao.test.model.JUser">

    </java>

    <java name="usersDelete" returnClass="java.lang.Void">

    </java>

    <java name="usersHead" returnClass="java.lang.Void">
    </java>

    <java name="usersOptions" returnClass="com.github.paohaijiao.model.JResult">

    </java>

    <java name="usersTrace" returnClass="java.lang.String">
    </java>

    <java name="upload" returnClass="java.lang.String">

    </java>

    <java name="upload1" returnClass="java.lang.String">
    </java>

    <java name="download" returnClass="byte[]">

    </java>

    <java name="uploadWithPostParams" returnClass="java.lang.String">
    </java>
</javas>
